<?php if(isset($_GET['mac'])){$servername="127.0.0.1";$username="radius";$password="radius";$dbname="radius";$conn=new mysqli($servername,$username,$password,$dbname);if($conn->connect_error){die("Koneksi database gagal: ".$conn->connect_error);}$mac_address=$_GET['mac'];$query="SELECT username, AcctStartTime,CASE WHEN AcctStopTime is NULL THEN timestampdiff(SECOND,AcctStartTime,NOW()) ELSE AcctSessionTime END AS AcctSessionTime,
				NASIPAddress,CalledStationId,FramedIPAddress,CallingStationId,AcctInputOctets,AcctOutputOctets 
				FROM radacct
				WHERE callingstationid = '$mac_address' ORDER BY RadAcctId DESC LIMIT 1";$result=$conn->query($query);$data=array();$sqlUser="SELECT username FROM radacct WHERE callingstationid='$mac_address' ORDER BY acctstarttime DESC LIMIT 1;";$resultUser=mysqli_fetch_assoc(mysqli_query($conn,$sqlUser));$user=$resultUser['username'];$sqlTotalSession="SELECT g.value as total_session FROM radgroupcheck as g, radusergroup as u WHERE u.username = '$user' AND g.groupname = u.groupname AND g.attribute ='Max-All-Session';";$resultTotalSession=mysqli_fetch_assoc(mysqli_query($conn,$sqlTotalSession));$totalSession=isset($resultTotalSession['total_session'])?$resultTotalSession['total_session']:0;$sqlTotalKuota="SELECT VALUE AS total_kuota
            FROM radgroupreply
            WHERE ATTRIBUTE = 'ChilliSpot-Max-Total-Octets'
              AND GROUPNAME = (
                SELECT GROUPNAME
                FROM radusergroup
                WHERE USERNAME = '$user'
              )";$resultTotalKuota=mysqli_fetch_assoc(mysqli_query($conn,$sqlTotalKuota));if(is_array($resultTotalKuota)&&isset($resultTotalKuota['total_kuota'])){$totalKuota=$resultTotalKuota['total_kuota'];}else{$totalKuota=0;}$sqlKuotaDigunakan="SELECT SUM(acctinputoctets + acctoutputoctets) as kuota_terpakai FROM radacct WHERE username = '$user';";$resultKuotaDigunakan=mysqli_fetch_assoc(mysqli_query($conn,$sqlKuotaDigunakan));$KuotaDigunakan=$resultKuotaDigunakan['kuota_terpakai'];$sqlFirstLogin="SELECT acctstarttime AS first_login FROM radacct WHERE username='$user' ORDER BY acctstarttime ASC LIMIT 1;";$resultFirstLogin=mysqli_fetch_assoc(mysqli_query($conn,$sqlFirstLogin));$firstLogin=$resultFirstLogin['first_login'];$duration=$totalSession;$expiryTime=strtotime($firstLogin)+$duration;$sisaKuota=$totalKuota-$KuotaDigunakan;$remainingTime=$expiryTime-time();if($result->num_rows>0){while($row=$result->fetch_assoc()){$username=$row['username'];$userUpload=toxbyte($row['AcctInputOctets']);$userDownload=toxbyte($row['AcctOutputOctets']);$userTraffic=toxbyte($row['AcctOutputOctets']+$row['AcctInputOctets']);$userLastConnected=$row['AcctStartTime'];$userOnlineTime=time2str($row['AcctSessionTime']);$nasIPAddress=$row['NASIPAddress'];$nasMacAddress=$row['CalledStationId'];$userIPAddress=$row['FramedIPAddress'];$userMacAddress=$row['CallingStationId'];$userExpired=time2str($remainingTime);$UserKuota=toxbyte($sisaKuota);$data=array('username'=>$username,'userIPAddress'=>$userIPAddress,'userMacAddress'=>$userMacAddress,'userDownload'=>$userDownload,'userUpload'=>$userUpload,'userTraffic'=>$userTraffic,'userLastConnected'=>$userLastConnected,'userOnlineTime'=>$userOnlineTime,'userExpired'=>$userExpired,'userKuota'=>$UserKuota,);}}$conn->close();echo json_encode($data);}function toxbyte($size){if($size>1073741824){return round($size/1073741824,2)." GB";}elseif($size>1048576){return round($size/1048576,2)." MB";}elseif($size>1024){return round($size/1024,2)." KB";}else{return $size." B";}}function time2str($time){$str="";$time=floor($time);if(!$time)return "0 detik";$d=$time/86400;$d=floor($d);if($d){$str.="$d hari, ";$time=$time%86400;}$h=$time/3600;$h=floor($h);if($h){$str.="$h jam, ";$time=$time%3600;}$m=$time/60;$m=floor($m);if($m){$str.="$m menit, ";$time=$time%60;}if($time)$str.="$time detik, ";$str=preg_replace("/, $/",'',$str);return $str;} ?>